# -*- coding: utf-8 -*-
"""TextSearchandReplace.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nGI156Yn5mNiw3USChah7cXTHQD4bANn
"""

# import all necessary modules
from google.colab import files
import re

fil = files.upload()

fil


key = list(fil.keys())
text = str(fil[key[0]])

text

sentence = "Hi, my name is Mike and I like to eat Mike's chocolates."

regex_name = re.compile('Mike')
regex_name.findall(sentence)

regex_name.sub("MIKE", sentence)
names = ['Adam', 'Bob', 'Charles']
for name in names:
  print(regex_name.sub(name, sentence))

sentence = "Hi, my name is Mike and I like to eat Muke's chocolates."

regex_name = re.compile(r'M\wke')
regex_name.findall(sentence)

# pattern to replace
'\\n\\n1\\n00:05.080 --> 00:09.310\\n'

pattern2replace = r'\\n\\n\d{1,3}\\n\d\d:\d\d.\d\d\d --> \d\d:\d\d.\d\d\d\\n'

regex_timestamps = re.compile(pattern2replace)
regex_timestamps.findall(text)

newtext = regex_timestamps.sub(' ', text)
newtext = newtext[9:-1]
newtext

words = newtext.split()

print(type(words))
print(len(words))
words[:30]

for wordi in range(len(words)):
  if len(words[wordi]) == 4 and not words[wordi][-1] == '.':
    words[wordi] = words[wordi][0] + '***'

#Join is a function that can join a set of strings. It starts with a delimiter denoted by quotes.
cleantext = ' '.join(words)

cleantext

with open('clean_transcript.txt','w') as f:
  f.write(cleantext)

files.download('clean_transcript.txt')